using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Football.Models;

namespace Football.Controllers
{
    public class PlayerController : Controller
    {
        private List<Player> Players = new List<Player>()
        {
            new Player{ PlayerId = 1,
                        PlayerName = "Moses",
                        PlayerAge = 25,
                        TeamName = "Manchester City",
                        NumberOfFans = 15000,
                        Position = "Most Popular",
                        AddComments = "Most Loved Player",
                        
            },
             new Player{ PlayerId = 2,
                        PlayerName = "Philip",
                        PlayerAge = 22,
                        TeamName = "Manchester City",
                        NumberOfFans = 13000,
                        Position = "Most Popular",
                        AddComments = "Most goals in 25 matches",
                        
            },
             new Player{ PlayerId = 3,
                        PlayerName = "Matac",
                        PlayerAge = 21,
                        TeamName = "Manchester City",
                        NumberOfFans = 12000,
                        Position = "Most Popular",
                        AddComments = "Calmest player in the young generation",
                        
            },
              new Player{ PlayerId = 4,
                        PlayerName = "Dhanik",
                        PlayerAge = 23,
                        TeamName = "Manchester City",
                        NumberOfFans = 18000,
                        Position = "Most Popular",
                        AddComments = "Loved by Girls",
                       
            },
              new Player{ PlayerId = 5,
                        PlayerName = "Zack",
                        PlayerAge = 30,
                        TeamName = "Manchester City",
                        NumberOfFans = 15000,
                        Position = "Most Popular",
                        AddComments = "handsome player in the team",
                       
              },
              new Player{ PlayerId = 6,
                        PlayerName = "Bob",
                        PlayerAge = 26,
                        TeamName = "Manchester United",
                        NumberOfFans = 100,
                        Position = "Most Popular",
                        AddComments = "Stylist of all of them",
                        
              },
                new Player{ PlayerId = 7,
                        PlayerName = "Matt",
                        PlayerAge = 32,
                        TeamName = "Manchester United",
                        NumberOfFans = 200,
                        Position = "Most Popular",
                        AddComments = "Cool caption",
                        
              },
                  new Player{ PlayerId = 8,
                        PlayerName = "Jack",
                        PlayerAge = 35,
                        TeamName = "Manchester United",
                        NumberOfFans = 1600,
                        Position = "Most Popular",
                        AddComments = "Quickest goal keeper",
                         

              },
                    new Player{ PlayerId = 9,
                        PlayerName = "Dan",
                        PlayerAge = 17,
                        TeamName = "Manchester United",
                        NumberOfFans = 1800,
                        Position = "Most Popular",
                        AddComments = "fast runner",
                         
              },
                      new Player{ PlayerId = 10,
                        PlayerName = "David",
                        PlayerAge = 18,
                        TeamName = "Manchester United",
                        NumberOfFans = 500,
                        Position = "Most Popular",
                        AddComments = "Animal lover",
                          
              },
                        new Player{ PlayerId = 11,
                        PlayerName = "Pulin",
                        PlayerAge = 20,
                        TeamName = "Leicester City",
                        NumberOfFans =300,
                        Position = "Most Popular",
                        AddComments = "Wrote a book on mother love",
                         
              },
                          new Player{ PlayerId = 12,
                        PlayerName = "Keian",
                        PlayerAge = 30,
                        TeamName = "Leicester City",
                        NumberOfFans = 156,
                        Position = "Most Popular",
                        AddComments = "Inspiration for young kids",
                         
              },
                            new Player{ PlayerId = 13,
                        PlayerName = "Cheslea",
                        PlayerAge = 35,
                        TeamName = "Leicester City",
                        NumberOfFans = 158,
                        Position = "Most Popular",
                        AddComments = "Loved by kids",
                         
              },
                              new Player{ PlayerId = 14,
                        PlayerName = "Rhyas",
                        PlayerAge = 32,
                        TeamName ="Leicester City",
                        NumberOfFans = 190,
                        Position = "Most Popular",
                        AddComments = "Tallest player in the team",
                         
              },
                                new Player{ PlayerId = 15,
                        PlayerName = "Ryan",
                        PlayerAge = 24,
                        TeamName = "Leicester City",
                        NumberOfFans = 189,
                        Position = "Most Popular",
                        AddComments = "Love to travel",
                        
              },
                                  new Player{ PlayerId = 16,
                        PlayerName = "Luke",
                        PlayerAge = 25,
                        TeamName = "West Ham United",
                        NumberOfFans = 167,
                        Position = "Most Popular",
                        AddComments = "Born in most romatic city Paris",
                         
              },
                          new Player{ PlayerId = 17,
                        PlayerName = "Darein",
                        PlayerAge = 27,
                        TeamName = "West Ham United",
                        NumberOfFans = 178,
                        Position = "Most Popular",
                        AddComments = "Kind to Animals",
                         
              },
                            new Player{ PlayerId = 18,
                        PlayerName = "Simpn",
                        PlayerAge = 29,
                        TeamName = "West Ham United",
                        NumberOfFans = 678,
                        Position = "Most Popular",
                        AddComments = "Belives in hard work",
                         
              },
                              new Player{ PlayerId = 19,
                        PlayerName = "Sam",
                        PlayerAge = 20,
                        TeamName = "West Ham United",
                        NumberOfFans = 167,
                        Position = "Most Popular",
                        AddComments = "Down to earth",
                         
              },
                                new Player{ PlayerId = 20,
                        PlayerName = "Luis",
                        PlayerAge = 17,
                        TeamName = "West Ham United",
                        NumberOfFans = 134,
                        Position = "Most Popular",
                        AddComments = "Angry player",
                         
              },
                                  new Player{ PlayerId = 21,
                        PlayerName = "Daniel",
                        PlayerAge = 27,
                        TeamName = "Liverpool",
                        NumberOfFans = 109,
                        Position = "Most Popular",
                        AddComments = "Born in India",
                        
              },
                          new Player{ PlayerId = 22,
                        PlayerName = "Whytt",
                        PlayerAge = 24,
                        TeamName = "Liverpool",
                        NumberOfFans = 198,
                        Position = "Most Popular",
                        AddComments = "Loves Animal",
                         
              },
                            new Player{ PlayerId = 23,
                        PlayerName = "Tom",
                        PlayerAge = 23,
                        TeamName = "Liverpool",
                        NumberOfFans = 300,
                        Position = "Most Popular",
                        AddComments = "Kids favourite",
                         
              },
                              new Player{ PlayerId = 24,
                        PlayerName = "Harry",
                        PlayerAge = 22,
                        TeamName = "Liverpool",
                        NumberOfFans = 1678,
                        Position = "Most Popular",
                        AddComments = "Born in england",
                         
              },
                                new Player{ PlayerId = 25,
                        PlayerName = "Jerry",
                        PlayerAge = 27,
                        TeamName = "Liverpool",
                        NumberOfFans = 980,
                        Position = "Most Popular",
                        AddComments = "Most experienced player",
                         
              },
                                  new Player{ PlayerId = 26,
                        PlayerName = "Pepa",
                        PlayerAge = 30,
                        TeamName = "Everton",
                        NumberOfFans = 349,
                        Position = "Most Popular",
                        AddComments = "Love to do charity",
                         
              },
                          new Player{ PlayerId = 27,
                        PlayerName = "Luicefer",
                        PlayerAge = 34,
                        TeamName = "Everton",
                        NumberOfFans = 457,
                        Position = "Most Popular",
                        AddComments = "Works out a lot",
                         
              },
                            new Player{ PlayerId = 28,
                        PlayerName = "Jordan",
                        PlayerAge = 30,
                        TeamName = "Everton",
                        NumberOfFans = 567,
                        Position = "Most Popular",
                        AddComments = "Belive in health eating",
                        
              },
                              new Player{ PlayerId = 29,
                        PlayerName = "Zen",
                        PlayerAge = 23,
                        TeamName = "Everton",
                        NumberOfFans = 897,
                        Position = "Most Popular",
                        AddComments = "Vegetarian player in the team",
                         
              },
                                new Player{ PlayerId = 30,
                        PlayerName = "Leo",
                        PlayerAge = 24,
                        TeamName = "Everton",
                        NumberOfFans = 908,
                        Position = "Most Popular",
                        AddComments = "Love to eat sausages",
                         
              },
                                  new Player{PlayerId = 28,
                        PlayerName = "Zack",
                        PlayerAge = 30,
                        TeamName = "Leeds United",
                        NumberOfFans = 739,
                        Position = "Most Popular",
                        AddComments = "Morning person ",
                         
              },
                          new Player{PlayerId = 32,
                        PlayerName = "Oek",
                        PlayerAge = 30,
                        TeamName = "Leeds United",
                        NumberOfFans = 457,
                        Position = "Most Popular",
                        AddComments = "Night owl",
                         
              },
                            new Player{ PlayerId = 33,
                        PlayerName = "Rompo",
                        PlayerAge = 30,
                        TeamName = "Leeds United",
                        NumberOfFans = 984,
                        Position = "Most Popular",
                        AddComments = "Sorted player in the team",
                         
              },
                              new Player{ PlayerId = 34,
                        PlayerName = "Krish",
                        PlayerAge = 23,
                        TeamName = "Leeds United",
                        NumberOfFans = 2347,
                        Position = "Most Popular",
                        AddComments = "Most calm",
                         
              },
                                new Player{ PlayerId = 35,
                        PlayerName = "Kar",
                        PlayerAge = 24,
                        TeamName ="Leeds United",
                        NumberOfFans = 490,
                        Position = "Most Popular",
                        AddComments = "Family guy",
                         
              },
                                  new Player{ PlayerId = 36,
                        PlayerName = "Cakgs",
                        PlayerAge = 32,
                        TeamName = "Arsenal",
                        NumberOfFans = 1565,
                        Position = "Most Popular",
                        AddComments = "mums boy",
                         
              },
                          new Player{ PlayerId = 37,
                        PlayerName = "Zoevy",
                        PlayerAge = 30,
                        TeamName = "Arsenal",
                        NumberOfFans = 456,
                        Position = "Most Popular",
                        AddComments = "Dadys boy",
                         
              },
                            new Player{ PlayerId = 38,
                        PlayerName = "Taary",
                        PlayerAge = 32,
                        TeamName = "Arsenal",
                        NumberOfFans = 150,
                        Position = "Most Popular",
                        AddComments = "Love to go on vacation",
                         
              },
                              new Player{ PlayerId = 39,
                        PlayerName = "Mic",
                        PlayerAge = 28,
                        TeamName = "Arsenal",
                        NumberOfFans = 290,
                        Position = "Most Popular",
                        AddComments = "Cool caption",
                         
              },
                                new Player{ PlayerId = 40,
                        PlayerName = "Cristy",
                        PlayerAge = 27,
                        TeamName = "Arsenal",
                        NumberOfFans = 1380,
                        Position = "Most Popular",
                        AddComments = "Love to watch movies",
                         
              },
                                  new Player{ PlayerId = 41,
                        PlayerName = "Poppy",
                        PlayerAge = 29,
                        TeamName = "Aston Villa",
                        NumberOfFans = 600,
                        Position = "Most Popular",
                        AddComments = "part time trainer",
                        
              },
                          new Player{ PlayerId = 42,
                        PlayerName = "Haary",
                        PlayerAge = 30,
                        TeamName = "Aston Villa",
                        NumberOfFans = 900,
                        Position = "Most Popular",
                        AddComments = "Love to cook",
                         
              },
                            new Player{ PlayerId = 43,
                        PlayerName = "Zome",
                        PlayerAge = 17,
                        TeamName = "Aston Villa",
                        NumberOfFans = 600,
                        Position = "Most Popular",
                        AddComments = "Love to eat different cuisine",
              },
                              new Player{ PlayerId = 44,
                        PlayerName = "Aame",
                        PlayerAge = 18,
                        TeamName ="Aston Villa",
                        NumberOfFans = 900,
                        Position = "Most Popular",
                        AddComments = "Chicken lover",
                        
              },
                                new Player{ PlayerId = 45,
                        PlayerName = "Popz",
                        PlayerAge = 20,
                        TeamName = "Aston Villa",
                        NumberOfFans = 890,
                        Position = "Most Popular",
                        AddComments = "Belive in clean eating ",
                         
              },
                                  new Player{ PlayerId = 46,
                        PlayerName = "Maathew",
                        PlayerAge = 31,
                        TeamName = "Fulham",
                        NumberOfFans = 5800,
                        Position = "Most Popular",
                        AddComments = "Never had alcohol",
                         
              },
                          new Player{ PlayerId = 47,
                        PlayerName = "Leo",
                        PlayerAge = 32,
                        TeamName = "Fulham",
                        NumberOfFans = 900,
                        Position = "Most Popular",
                        AddComments = "No smokig",
                         
              },
                            new Player{ PlayerId = 48,
                        PlayerName = "Papzy",
                        PlayerAge = 30,
                        TeamName ="Fulham",
                        NumberOfFans = 500,
                        Position = "Most Popular",
                        AddComments = "Loves animals",
                         
              },
                              new Player{ PlayerId = 49,
                        PlayerName = "Shivangi",
                        PlayerAge = 20,
                        TeamName = "Fulham",
                        NumberOfFans = 159000,
                        AddComments = "Most crazy person",
                        Position = "Most Popular",
                         
                         
              },
                         new Player{ PlayerId = 50,
                        PlayerName = "Maitri",
                        PlayerAge = 20,
                        TeamName ="Fulham",
                        NumberOfFans = 569000,
                        AddComments = "Most crazy person ",
                        Position = "Most Popular",
                         
                         
              },
        };
        // GET: Product
        public ActionResult Index()
        {
            return View(Players);
        }

        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpNotFoundResult();
            Player selectedPlayer = Players.First(p => p.PlayerId == id);

            if (selectedPlayer == null) return new HttpNotFoundResult();

            return View(selectedPlayer);
        }
        // GET: Edit/id 
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpNotFoundResult();
            Player selectedPlayer = Players.First(p => p.PlayerId == id);
            if (selectedPlayer == null) return new HttpNotFoundResult();
            return View(selectedPlayer);
        }
    }
}